name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from Git tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build Docker image (versioned)
        if: env.VERSION != ''
        run: |
          docker build -t henryggg/mi-web-docker:${VERSION} .
          docker tag henryggg/mi-web-docker:${VERSION} henryggg/mi-web-docker:latest

      - name: Push Docker image (versioned)
        if: env.VERSION != ''
        run: |
          docker push henryggg/mi-web-docker:${VERSION}
          docker push henryggg/mi-web-docker:latest